# WHERE
조건에 맞는 데이터만 가져올 수 있습니다.  
`
SELEECT
    컬럼명  
FROM  
    테이블명  
WHERE  
    조건문  
`


연산자를 이용하여 조건문을 작성할 수 있습니다.

연산자
* [비교연산자](#비교-연산자)
* 논리연산자

## 비교 연산자
|연산자|의미|
|---|---|
|=|일치하는 경우|
|!=|일치하지 않는 경우|
|<|해당 값 **미만**인 경우|
|<=|해당 값 **이하**인 경우|
|>|해당 값 **초과**인 경우|
|>=|해당 값 **이상**인 경우|

In [2]:
import sqlite3
from prettytable import from_db_cursor

# SQLite 데이터베이스에 연결하기 위해 connect 생성
con = sqlite3.connect('./database/chinook.db')
con.row_factory = sqlite3.Row

# cursor 생성
cur = con.cursor()

In [2]:
# customerid가 5 이하인 경우
cur.execute("""
    SELECT *
    FROM customers
    WHERE customerid <= 5
    """)

from_db_cursor(cur)

+------------+-----------+-------------+--------------------------------------------------+---------------------------------+---------------------+-------+----------------+------------+--------------------+--------------------+--------------------------+--------------+
| CustomerId | FirstName |   LastName  |                     Company                      |             Address             |         City        | State |    Country     | PostalCode |       Phone        |        Fax         |          Email           | SupportRepId |
+------------+-----------+-------------+--------------------------------------------------+---------------------------------+---------------------+-------+----------------+------------+--------------------+--------------------+--------------------------+--------------+
|     1      |    Luís   |  Gonçalves  | Embraer - Empresa Brasileira de Aeronáutica S.A. | Av. Brigadeiro Faria Lima, 2170 | São José dos Campos |   SP  |     Brazil     | 12227-000  | +55 (12) 3923-5555 | +55 (12) 3923-5566 |   luisg@embraer.com.br   |      3       |
|     2      |   Leonie  |    Köhler   |                       None                       |     Theodor-Heuss-Straße 34     |      Stuttgart      |  None |    Germany     |   70174    |  +49 0711 2842222  |        None        |  leonekohler@surfeu.de   |      5       |
|     3      |  François |   Tremblay  |                       None                       |        1498 rue Bélanger        |       Montréal      |   QC  |     Canada     |  H2G 1A7   | +1 (514) 721-4711  |        None        |   ftremblay@gmail.com    |      3       |
|     4      |   Bjørn   |    Hansen   |                       None                       |         Ullevålsveien 14        |         Oslo        |  None |     Norway     |    0171    |  +47 22 44 22 22   |        None        |  bjorn.hansen@yahoo.no   |      4       |
|     5      | František | Wichterlová |                 JetBrains s.r.o.                 |          Klanova 9/506          |        Prague       |  None | Czech Republic |   14700    |  +420 2 4172 5555  |  +420 2 4172 5555  | frantisekw@jetbrains.com |      4       |
+------------+-----------+-------------+--------------------------------------------------+---------------------------------+---------------------+-------+----------------+------------+--------------------+--------------------+--------------------------+--------------+

## 논리연산자

|연산자|의미|
|---|---|
|AND|두 식을 결합하여 두 식이 모두 참인경우 1 (True), 그렇지 않은 경우 0 (False)|
|OR|두 식을 결합하여 두 식 중 하나라도 참인경우 1 (True), 그렇지 않은 경우 0 (False)|
|NOT|해당 연산이 참이 아닌 경우 (ex. NOT IN, NOT EXISTS, NOT BETWEEN)|
|BETWEEN|지정한 범위 내의 값인 경우|
|IN|IN 뒤의 값에 포함되는 값인 경우|
|LIKE|패턴에 맞는 값인 경우|

In [21]:
cur.execute("""
    SELECT * 
    FROM employees
    WHERE lastname = 'Adams' and firstname = 'Andrew'
    """)
from_db_cursor(cur)

+------------+----------+-----------+-----------------+-----------+---------------------+---------------------+---------------------+----------+-------+---------+------------+-------------------+-------------------+------------------------+
| EmployeeId | LastName | FirstName |      Title      | ReportsTo |      BirthDate      |       HireDate      |       Address       |   City   | State | Country | PostalCode |       Phone       |        Fax        |         Email          |
+------------+----------+-----------+-----------------+-----------+---------------------+---------------------+---------------------+----------+-------+---------+------------+-------------------+-------------------+------------------------+
|     1      |  Adams   |   Andrew  | General Manager |    None   | 1962-02-18 00:00:00 | 2002-08-14 00:00:00 | 11120 Jasper Ave NW | Edmonton |   AB  |  Canada |  T5K 2N1   | +1 (780) 428-9482 | +1 (780) 428-3457 | andrew@chinookcorp.com |
+------------+----------+-----------+-----------------+-----------+---------------------+---------------------+---------------------+----------+-------+---------+------------+-------------------+-------------------+------------------------+

### BETWEEN
지정한 범위 내의 값이면 참입니다.

In [22]:
# BETWEEN a AND b -> a~b 범위 안이면 참 (a, b 포함)
cur.execute("""
    SELECT *
    FROM customers
    WHERE customerid BETWEEN 15 AND 20
    """)

from_db_cursor(cur)

+------------+-----------+----------+-----------------------+---------------------------+---------------+-------+---------+------------+-------------------+-------------------+-------------------------+--------------+
| CustomerId | FirstName | LastName |        Company        |          Address          |      City     | State | Country | PostalCode |       Phone       |        Fax        |          Email          | SupportRepId |
+------------+-----------+----------+-----------------------+---------------------------+---------------+-------+---------+------------+-------------------+-------------------+-------------------------+--------------+
|     15     |  Jennifer | Peterson |     Rogers Canada     |    700 W Pender Street    |   Vancouver   |   BC  |  Canada |  V6C 1G8   | +1 (604) 688-2255 | +1 (604) 688-8756 |   jenniferp@rogers.ca   |      3       |
|     16     |   Frank   |  Harris  |      Google Inc.      | 1600 Amphitheatre Parkway | Mountain View |   CA  |   USA   | 94043-1351 | +1 (650) 253-0000 | +1 (650) 253-0000 |    fharris@google.com   |      4       |
|     17     |    Jack   |  Smith   | Microsoft Corporation |      1 Microsoft Way      |    Redmond    |   WA  |   USA   | 98052-8300 | +1 (425) 882-8080 | +1 (425) 882-8081 | jacksmith@microsoft.com |      5       |
|     18     |  Michelle |  Brooks  |          None         |        627 Broadway       |    New York   |   NY  |   USA   | 10012-2612 | +1 (212) 221-3546 | +1 (212) 221-4679 |    michelleb@aol.com    |      3       |
|     19     |    Tim    |  Goyer   |       Apple Inc.      |      1 Infinite Loop      |   Cupertino   |   CA  |   USA   |   95014    | +1 (408) 996-1010 | +1 (408) 996-1011 |     tgoyer@apple.com    |      3       |
|     20     |    Dan    |  Miller  |          None         |    541 Del Medio Avenue   | Mountain View |   CA  |   USA   | 94040-111  | +1 (650) 644-3358 |        None       |   dmiller@comcast.com   |      4       |
+------------+-----------+----------+-----------------------+---------------------------+---------------+-------+---------+------------+-------------------+-------------------+-------------------------+--------------+

### IN
지정한 목록에 있는 값 중 하나와 일치하면 참입니다.

In [23]:
cur.execute("""
    SELECT *
    FROM customers
    WHERE customerid IN (1, 5, 10)
    """)

from_db_cursor(cur)

+------------+-----------+-------------+--------------------------------------------------+---------------------------------+---------------------+-------+----------------+------------+--------------------+--------------------+--------------------------+--------------+
| CustomerId | FirstName |   LastName  |                     Company                      |             Address             |         City        | State |    Country     | PostalCode |       Phone        |        Fax         |          Email           | SupportRepId |
+------------+-----------+-------------+--------------------------------------------------+---------------------------------+---------------------+-------+----------------+------------+--------------------+--------------------+--------------------------+--------------+
|     1      |    Luís   |  Gonçalves  | Embraer - Empresa Brasileira de Aeronáutica S.A. | Av. Brigadeiro Faria Lima, 2170 | São José dos Campos |   SP  |     Brazil     | 12227-000  | +55 (12) 3923-5555 | +55 (12) 3923-5566 |   luisg@embraer.com.br   |      3       |
|     5      | František | Wichterlová |                 JetBrains s.r.o.                 |          Klanova 9/506          |        Prague       |  None | Czech Republic |   14700    |  +420 2 4172 5555  |  +420 2 4172 5555  | frantisekw@jetbrains.com |      4       |
|     10     |  Eduardo  |   Martins   |                 Woodstock Discos                 |    Rua Dr. Falcão Filho, 155    |      São Paulo      |   SP  |     Brazil     | 01007-010  | +55 (11) 3033-5446 | +55 (11) 3033-4564 | eduardo@woodstock.com.br |      4       |
+------------+-----------+-------------+--------------------------------------------------+---------------------------------+---------------------+-------+----------------+------------+--------------------+--------------------+--------------------------+--------------+

### LIKE
패턴과 일치하는 경우 참입니다.  
%와 _를 이용하여 패턴을 지정할 수 있습니다.  
%와 _는 모든 문자와 매칭되며, %는 문자열, _는 문자 하나를 의미합니다.

In [24]:
# 전화번호가 +55로 시작하는 경우
cur.execute("""
    SELECT *
    FROM customers
    WHERE phone LIKE '+55%'
    """)

from_db_cursor(cur)

+------------+-----------+-----------+--------------------------------------------------+---------------------------------+---------------------+-------+---------+------------+--------------------+--------------------+-------------------------------+--------------+
| CustomerId | FirstName |  LastName |                     Company                      |             Address             |         City        | State | Country | PostalCode |       Phone        |        Fax         |             Email             | SupportRepId |
+------------+-----------+-----------+--------------------------------------------------+---------------------------------+---------------------+-------+---------+------------+--------------------+--------------------+-------------------------------+--------------+
|     1      |    Luís   | Gonçalves | Embraer - Empresa Brasileira de Aeronáutica S.A. | Av. Brigadeiro Faria Lima, 2170 | São José dos Campos |   SP  |  Brazil | 12227-000  | +55 (12) 3923-5555 | +55 (12) 3923-5566 |      luisg@embraer.com.br     |      3       |
|     10     |  Eduardo  |  Martins  |                 Woodstock Discos                 |    Rua Dr. Falcão Filho, 155    |      São Paulo      |   SP  |  Brazil | 01007-010  | +55 (11) 3033-5446 | +55 (11) 3033-4564 |    eduardo@woodstock.com.br   |      4       |
|     11     | Alexandre |   Rocha   |               Banco do Brasil S.A.               |        Av. Paulista, 2022       |      São Paulo      |   SP  |  Brazil | 01310-200  | +55 (11) 3055-3278 | +55 (11) 3055-8131 |        alero@uol.com.br       |      5       |
|     12     |  Roberto  |  Almeida  |                      Riotur                      |         Praça Pio X, 119        |    Rio de Janeiro   |   RJ  |  Brazil | 20040-020  | +55 (21) 2271-7000 | +55 (21) 2271-7070 | roberto.almeida@riotur.gov.br |      3       |
|     13     |  Fernanda |   Ramos   |                       None                       |           Qe 7 Bloco G          |       Brasília      |   DF  |  Brazil | 71020-677  | +55 (61) 3363-5547 | +55 (61) 3363-7855 |    fernadaramos4@uol.com.br   |      4       |
+------------+-----------+-----------+--------------------------------------------------+---------------------------------+---------------------+-------+---------+------------+--------------------+--------------------+-------------------------------+--------------+

In [25]:
# 전화번호에 00을 포함하는 경우
cur.execute("""
    SELECT *
    FROM customers
    WHERE phone LIKE '%00%'
    """)

from_db_cursor(cur)

+------------+-----------+------------+-------------+---------------------------+----------------+-------+----------------+------------+--------------------+--------------------+-------------------------------+--------------+
| CustomerId | FirstName |  LastName  |   Company   |          Address          |      City      | State |    Country     | PostalCode |       Phone        |        Fax         |             Email             | SupportRepId |
+------------+-----------+------------+-------------+---------------------------+----------------+-------+----------------+------------+--------------------+--------------------+-------------------------------+--------------+
|     12     |  Roberto  |  Almeida   |    Riotur   |      Praça Pio X, 119     | Rio de Janeiro |   RJ  |     Brazil     | 20040-020  | +55 (21) 2271-7000 | +55 (21) 2271-7070 | roberto.almeida@riotur.gov.br |      3       |
|     16     |   Frank   |   Harris   | Google Inc. | 1600 Amphitheatre Parkway | Mountain View  |   CA  |      USA       | 94043-1351 | +1 (650) 253-0000  | +1 (650) 253-0000  |       fharris@google.com      |      4       |
|     27     |  Patrick  |    Gray    |     None    |      1033 N Park Ave      |     Tucson     |   AZ  |      USA       |   85719    | +1 (520) 622-4200  |        None        |      patrick.gray@aol.com     |      4       |
|     44     |   Terhi   | Hämäläinen |     None    |      Porthaninkatu 9      |    Helsinki    |  None |    Finland     |   00530    |  +358 09 870 2000  |        None        |   terhi.hamalainen@apple.fi   |      3       |
|     54     |   Steve   |   Murray   |     None    |       110 Raeburn Pl      |   Edinburgh    |  None | United Kingdom |  EH4 1HH   | +44 0131 315 3300  |        None        |     steve.murray@yahoo.uk     |      5       |
+------------+-----------+------------+-------------+---------------------------+----------------+-------+----------------+------------+--------------------+--------------------+-------------------------------+--------------+

In [27]:
# 성이 on으로 끝나는 경우
cur.execute("""
    SELECT *
    FROM customers
    WHERE lastname LIKE '%on'
    """)

from_db_cursor(cur)

+------------+-----------+-----------+---------------+-----------------------+-----------+-------+---------+------------+-------------------+-------------------+---------------------------+--------------+
| CustomerId | FirstName |  LastName |    Company    |        Address        |    City   | State | Country | PostalCode |       Phone       |        Fax        |           Email           | SupportRepId |
+------------+-----------+-----------+---------------+-----------------------+-----------+-------+---------+------------+-------------------+-------------------+---------------------------+--------------+
|     15     |  Jennifer |  Peterson | Rogers Canada |  700 W Pender Street  | Vancouver |   BC  |  Canada |  V6C 1G8   | +1 (604) 688-2255 | +1 (604) 688-8756 |    jenniferp@rogers.ca    |      3       |
|     23     |    John   |   Gordon  |      None     |    69 Salem Street    |   Boston  |   MA  |   USA   |    2113    | +1 (617) 522-1333 |        None       |   johngordon22@yahoo.com  |      4       |
|     24     |   Frank   |  Ralston  |      None     | 162 E Superior Street |  Chicago  |   IL  |   USA   |   60611    | +1 (312) 332-3232 |        None       |     fralston@gmail.com    |      3       |
|     51     |   Joakim  | Johansson |      None     |      Celsiusg. 9      | Stockholm |  None |  Sweden |   11230    |  +46 08-651 52 52 |        None       | joakim.johansson@yahoo.se |      5       |
+------------+-----------+-----------+---------------+-----------------------+-----------+-------+---------+------------+-------------------+-------------------+---------------------------+--------------+

In [28]:
# state가 B로 끝나는 2글자인 경우
cur.execute("""
    SELECT *
    FROM customers
    WHERE state LIKE '_B'
    """)

from_db_cursor(cur)

+------------+-----------+----------+---------+--------------------+----------+-------+---------+------------+-------------------+-------------------+------------------------+--------------+
| CustomerId | FirstName | LastName | Company |      Address       |   City   | State | Country | PostalCode |       Phone       |        Fax        |         Email          | SupportRepId |
+------------+-----------+----------+---------+--------------------+----------+-------+---------+------------+-------------------+-------------------+------------------------+--------------+
|     14     |    Mark   | Philips  |  Telus  |   8210 111 ST NW   | Edmonton |   AB  |  Canada |  T6G 2C7   | +1 (780) 434-4554 | +1 (780) 434-5565 |   mphilips12@shaw.ca   |      5       |
|     32     |   Aaron   | Mitchell |   None  | 696 Osborne Street | Winnipeg |   MB  |  Canada |  R3L 2B9   | +1 (204) 452-6452 |        None       | aaronmitchell@yahoo.ca |      4       |
+------------+-----------+----------+---------+--------------------+----------+-------+---------+------------+-------------------+-------------------+------------------------+--------------+

In [29]:
# state가 S로 시작하는 두글자일 경우
cur.execute("""
    SELECT *
    FROM customers
    WHERE state LIKE 'S_'
    """)

from_db_cursor(cur)

+------------+-----------+-----------+--------------------------------------------------+---------------------------------+---------------------+-------+---------+------------+--------------------+--------------------+--------------------------+--------------+
| CustomerId | FirstName |  LastName |                     Company                      |             Address             |         City        | State | Country | PostalCode |       Phone        |        Fax         |          Email           | SupportRepId |
+------------+-----------+-----------+--------------------------------------------------+---------------------------------+---------------------+-------+---------+------------+--------------------+--------------------+--------------------------+--------------+
|     1      |    Luís   | Gonçalves | Embraer - Empresa Brasileira de Aeronáutica S.A. | Av. Brigadeiro Faria Lima, 2170 | São José dos Campos |   SP  |  Brazil | 12227-000  | +55 (12) 3923-5555 | +55 (12) 3923-5566 |   luisg@embraer.com.br   |      3       |
|     10     |  Eduardo  |  Martins  |                 Woodstock Discos                 |    Rua Dr. Falcão Filho, 155    |      São Paulo      |   SP  |  Brazil | 01007-010  | +55 (11) 3033-5446 | +55 (11) 3033-4564 | eduardo@woodstock.com.br |      4       |
|     11     | Alexandre |   Rocha   |               Banco do Brasil S.A.               |        Av. Paulista, 2022       |      São Paulo      |   SP  |  Brazil | 01310-200  | +55 (11) 3055-3278 | +55 (11) 3055-8131 |     alero@uol.com.br     |      5       |
+------------+-----------+-----------+--------------------------------------------------+---------------------------------+---------------------+-------+---------+------------+--------------------+--------------------+--------------------------+--------------+

In [30]:
# email 도메인이 2글자인 경우 (. 뒤에 2글자인 경우) 5개만 값 가져오기
cur.execute("""
    SELECT *
    FROM customers
    WHERE email LIKE '%.__'
    LIMIT 5
    """)

from_db_cursor(cur)

+------------+-----------+-----------+--------------------------------------------------+--------------------------------------+---------------------+-------+---------+------------+--------------------+--------------------+------------------------+--------------+
| CustomerId | FirstName |  LastName |                     Company                      |               Address                |         City        | State | Country | PostalCode |       Phone        |        Fax         |         Email          | SupportRepId |
+------------+-----------+-----------+--------------------------------------------------+--------------------------------------+---------------------+-------+---------+------------+--------------------+--------------------+------------------------+--------------+
|     1      |    Luís   | Gonçalves | Embraer - Empresa Brasileira de Aeronáutica S.A. |   Av. Brigadeiro Faria Lima, 2170    | São José dos Campos |   SP  |  Brazil | 12227-000  | +55 (12) 3923-5555 | +55 (12) 3923-5566 |  luisg@embraer.com.br  |      3       |
|     2      |   Leonie  |   Köhler  |                       None                       |       Theodor-Heuss-Straße 34        |      Stuttgart      |  None | Germany |   70174    |  +49 0711 2842222  |        None        | leonekohler@surfeu.de  |      5       |
|     4      |   Bjørn   |   Hansen  |                       None                       |           Ullevålsveien 14           |         Oslo        |  None |  Norway |    0171    |  +47 22 44 22 22   |        None        | bjorn.hansen@yahoo.no  |      4       |
|     7      |   Astrid  |   Gruber  |                       None                       | Rotenturmstraße 4, 1010 Innere Stadt |        Vienne       |  None | Austria |    1010    |   +43 01 5134505   |        None        | astrid.gruber@apple.at |      5       |
|     8      |    Daan   |  Peeters  |                       None                       |           Grétrystraat 63            |       Brussels      |  None | Belgium |    1000    |  +32 02 219 03 03  |        None        | daan_peeters@apple.be  |      4       |
+------------+-----------+-----------+--------------------------------------------------+--------------------------------------+---------------------+-------+---------+------------+--------------------+--------------------+------------------------+--------------+

In [31]:
# datetime도 가능
cur.execute("""
    SELECT *
    FROM employees
    WHERE hiredate LIKE '2003-10-17%'
    """)

from_db_cursor(cur)

+------------+----------+-----------+---------------------+-----------+---------------------+---------------------+----------------------+---------+-------+---------+------------+-------------------+-------------------+-------------------------+
| EmployeeId | LastName | FirstName |        Title        | ReportsTo |      BirthDate      |       HireDate      |       Address        |   City  | State | Country | PostalCode |       Phone       |        Fax        |          Email          |
+------------+----------+-----------+---------------------+-----------+---------------------+---------------------+----------------------+---------+-------+---------+------------+-------------------+-------------------+-------------------------+
|     5      | Johnson  |   Steve   | Sales Support Agent |     2     | 1965-03-03 00:00:00 | 2003-10-17 00:00:00 |     7727B 41 Ave     | Calgary |   AB  |  Canada |  T3B 1Y7   |  1 (780) 836-9987 |  1 (780) 836-9543 |  steve@chinookcorp.com  |
|     6      | Mitchell |  Michael  |      IT Manager     |     1     | 1973-07-01 00:00:00 | 2003-10-17 00:00:00 | 5827 Bowness Road NW | Calgary |   AB  |  Canada |  T3B 0C5   | +1 (403) 246-9887 | +1 (403) 246-9899 | michael@chinookcorp.com |
+------------+----------+-----------+---------------------+-----------+---------------------+---------------------+----------------------+---------+-------+---------+------------+-------------------+-------------------+-------------------------+

In [10]:
# = 와 같이 사용할수도 있음
cur.execute("""
    SELECT *
    FROM customers
    WHERE state LIKE 'SP'
    """)

from_db_cursor(cur)

+------------+-----------+-----------+--------------------------------------------------+---------------------------------+---------------------+-------+---------+------------+--------------------+--------------------+--------------------------+--------------+
| CustomerId | FirstName |  LastName |                     Company                      |             Address             |         City        | State | Country | PostalCode |       Phone        |        Fax         |          Email           | SupportRepId |
+------------+-----------+-----------+--------------------------------------------------+---------------------------------+---------------------+-------+---------+------------+--------------------+--------------------+--------------------------+--------------+
|     1      |    Luís   | Gonçalves | Embraer - Empresa Brasileira de Aeronáutica S.A. | Av. Brigadeiro Faria Lima, 2170 | São José dos Campos |   SP  |  Brazil | 12227-000  | +55 (12) 3923-5555 | +55 (12) 3923-5566 |   luisg@embraer.com.br   |      3       |
|     10     |  Eduardo  |  Martins  |                 Woodstock Discos                 |    Rua Dr. Falcão Filho, 155    |      São Paulo      |   SP  |  Brazil | 01007-010  | +55 (11) 3033-5446 | +55 (11) 3033-4564 | eduardo@woodstock.com.br |      4       |
|     11     | Alexandre |   Rocha   |               Banco do Brasil S.A.               |        Av. Paulista, 2022       |      São Paulo      |   SP  |  Brazil | 01310-200  | +55 (11) 3055-3278 | +55 (11) 3055-8131 |     alero@uol.com.br     |      5       |
+------------+-----------+-----------+--------------------------------------------------+---------------------------------+---------------------+-------+---------+------------+--------------------+--------------------+--------------------------+--------------+